### ISSUE TITLE
Thymeleaf plugin does not work in STS 4.9.0 (Eclipse 2020-12)

### ISSUE THREAD

**Issue by manueljordan** [thymeleaf/thymeleaf-extras-eclipse-plugin#99] opened 2021-01-04 15:20 UTC
Hello Thymelead Developers

Having:

![01](https://user-images.githubusercontent.com/2552795/103549419-55a5c700-4e75-11eb-9a5d-b38c5d1841b3.png)

and the Thymeleaf plugin

![02](https://user-images.githubusercontent.com/2552795/103549423-56d6f400-4e75-11eb-9ec0-5d8f445c1ccc.png)

For a Spring Boot (2.4.1) app with Thymeleaf, doing the following

![03](https://user-images.githubusercontent.com/2552795/103549427-58a0b780-4e75-11eb-85d7-0e1b086f470f.png)

Does not work (BTW - the `Error Log` view shows nothing)

Having the following header:

![04](https://user-images.githubusercontent.com/2552795/103549428-58a0b780-4e75-11eb-9772-31b84dbfb8ac.png)

Now in some point randomly appears:

![05](https://user-images.githubusercontent.com/2552795/103549429-59394e00-4e75-11eb-8fcc-3ee6a0034d6e.png)

And the Plugin does not work how is expected.

![06](https://user-images.githubusercontent.com/2552795/103549430-59394e00-4e75-11eb-95c5-4a030b05c6e1.png)

Now sure what could be.

**Comment by manueljordan** [comment] 2021-01-04 20:40
Some times when the `Add Thymeleaf Nature` is triggered manually it shows 

![Screen Shot 2021-01-04 at 3 39 02 PM](https://user-images.githubusercontent.com/2552795/103577634-2c9c2b00-4ea3-11eb-922d-b0c265a97e1d.png)

**Comment by user20161119** [comment] 2021-01-22 01:34
the same version as you,got this error after install plugin

![image](https://user-images.githubusercontent.com/123967/105433681-0d6c0e80-5c95-11eb-8a9c-3e4a677f3438.png)

**Comment by manueljordan** [comment] 2021-01-22 21:49
Thanks for that figure, yes. I think that I got the same message but I didn't take a screenshot about that

**Comment by kaiwinter** [comment] 2021-09-08 11:18
The root cause here is this exception:
```
Caused by: java.lang.ClassNotFoundException: javax.activation.DataSource cannot be found by org.thymeleaf.extras.eclipse.core_3.0.0.202005310144
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:519)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:170)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
```
JDK 11 misses this package but STS requires JDK 11. So I think this plugin has to be updated to be JDK 11 compatible. This issue is a duplicate of #100. Unfortunately I couldn't manage to build and test this plugin.

**Comment by ultraq** [comment] 2021-09-09 07:03
I thought I managed to fix up the Java 11 issues back in #84 (and many related issues to that) by bundling javax.activation and friends with the plugin 🤔  I'll check the build again and try w/ STS this time since you're saying it requires JDK11 now (I have a bunch of JDKs on my machine so I'm not always sure what Eclipse is using what JDK).

**Comment by kaiwinter** [comment] 2021-09-09 08:18
Thanks for your reply 😃  Here is an example of my `SpringToolSuite4.ini` which is pretty identical to `eclipse.ini`. The `-vm` arg defines the JDK which gets used for running eclipse/STS:
```
-vm
C:/dev/Java/jdk-11.0.6+10/bin
-startup
plugins/org.eclipse.equinox.launcher_1.6.200.v20210416-2027.jar
--launcher.library
plugins/org.eclipse.equinox.launcher.win32.win32.x86_64_1.2.200.v20210429-1609
-product
org.springframework.boot.ide.branding.sts4
--launcher.defaultAction
openFile
-vmargs
-javaagent:C:\dev\eclipse\sts-4.5.1.RELEASE\lombok.jar
-Dosgi.requiredJavaVersion=11
-Dosgi.dataAreaRequiresExplicitInit=true
-Xms512m
-Xmx6000m
--illegal-access=permit
--add-modules=ALL-SYSTEM
```

**Comment by ultraq** [comment] 2021-09-09 10:57
Had a look at this, and I think STS won't work with this plugin any more.  Even after looking into the bundled javax.activation JAR, I'm getting build errors everywhere using STS.  It seems that, as of STS 4.8.0, they started moving to a different editor for web development to something called Wild Web Developer (https://github.com/spring-projects/sts4/issues/354).  This plugin was written atop the Eclipse's Web Tools Platform (WTP) project instead, which ships as part of the "Eclipse for Java and Web developers" edition from the Eclipse website.

Thymeleaf support in WWD would be a much bigger project than simply fixing the bundled JARs... 🤔

**Comment by kaiwinter** [comment] 2021-09-09 17:35
Ah ok I see. Well that's bad news. I was always hoping this plugin may be extended to provide an even better Thymeleaf integration in Eclipse.

**Comment by manueljordan** [comment] 2021-09-10 14:54
I think STS would give support (for integration for both) - I don't see a reason to isolate thymeleaf plugin

**Comment by ultraq** [comment] 2021-09-12 06:27
I've just released a version 3.0.1 of the plugin which now bundles all of the JARs for all of the dependencies of the plugin, instead of relying on the the IDE to already include them.  Testing in both Eclipse 2021-06 and Spring Tool Suite 4.7.1, this should help fix up the javax.activation errors.

As for it working in STS 4.8.0 and newer, I'll use #92 for that.

**Closed as completed by ultraq** 2021-09-12 06:27 UTC
Labels: tracker:problem, status:done, eclipse compatibility

**Comment by kaiwinter** [comment] 2021-09-12 07:26
I'm using STS 4.11.1.RELEASE and it's working here too! Thanks for your quick fix 🥳

**Comment by ultraq** [comment] 2021-09-13 06:36
Oh nice, I might have to update that little note about 4.8.0+ that I added to the readme! 😅
